# Generated by Django 6.0.3 on 2026-03-20 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_meta', models.CharField(choices=[('peso', 'Peso'), ('gordura', '% de gordura'), ('massa_magra', 'Massa magra'), ('cintura', 'Cintura'), ('agua', 'Consumo de água'), ('sono', 'Horas de sono')], max_length=20)),
                ('valor_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_inicio', models.DateField()),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta fitness',
                'verbose_name_plural': 'Metas fitness',
                'ordering': ['status', 'data_limite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('objetivo', models.CharField(choices=[('perder_gordura', 'Perder gordura'), ('manter', 'Manter peso'), ('ganhar_massa', 'Ganhar massa'), ('recomposicao', 'Recomposição corporal')], default='manter', max_length=20)),
                ('nivel_atividade', models.CharField(choices=[('sedentario', 'Sedentário'), ('leve', 'Levemente ativo'), ('moderado', 'Moderadamente ativo'), ('alto', 'Muito ativo'), ('atleta', 'Atleta')], default='moderado', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil fitness',
                'verbose_name_plural': 'Perfis fitness',
            },
        ),
        migrations.CreateModel(
            name='PhysicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('idade_no_momento', models.PositiveIntegerField(blank=True, null=True)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('massa_magra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('massa_gorda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pescoco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ombro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('torax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('antebraco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('antebraco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=20)),
                ('frequencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('horas_sono', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('consumo_agua_litros', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classificacao_imc', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetabolicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('get', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estrategia_calorica', models.CharField(choices=[('deficit', 'Déficit calórico'), ('manutencao', 'Manutenção'), ('superavit', 'Superávit calórico')], default='manutencao', max_length=20)),
                ('calorias_meta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calorias_gasto_meta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proteina_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carboidrato_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gordura_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('proteina_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carboidrato_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gordura_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metabolic_plan', to='health.physicalassessment')),
            ],
            options={
                'verbose_name': 'Plano metabólico',
                'verbose_name_plural': 'Planos metabólicos',
            },
        ),
    ]
