# Generated by Django 6.0.3 on 2026-04-09 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalassessment',
            options={'ordering': ['-data_avaliacao', '-id'], 'verbose_name': 'Avaliação física', 'verbose_name_plural': 'Avaliações físicas'},
        ),
        migrations.AlterField(
            model_name='physicalassessment',
            name='data_avaliacao',
            field=models.DateField(db_index=True),
        ),
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('horas_sono', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('consumo_agua_litros', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('treinou', models.BooleanField(default=False)),
                ('minutos_treino', models.PositiveIntegerField(blank=True, null=True)),
                ('passos', models.PositiveIntegerField(blank=True, null=True)),
                ('aderencia_dieta', models.PositiveIntegerField(blank=True, help_text='Percentual de aderência da dieta no dia (0 a 100).', null=True)),
                ('humor', models.CharField(blank=True, choices=[('terrivel', 'Terrível'), ('ruim', 'Ruim'), ('ok', 'Ok'), ('bom', 'Bom'), ('excelente', 'Excelente')], max_length=20)),
                ('energia', models.CharField(blank=True, choices=[('muito_baixa', 'Muito baixa'), ('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('muito_alta', 'Muito alta')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-in diário',
                'verbose_name_plural': 'Check-ins diários',
                'ordering': ['-data', '-id'],
                'unique_together': {('user', 'data')},
            },
        ),
    ]
