# Generated by Django 6.0.3 on 2026-03-17 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('electronics', 'Eletrônicos'), ('books', 'Livros'), ('home', 'Casa'), ('fashion', 'Roupas'), ('games', 'Games'), ('office', 'Escritório'), ('online', 'Compras online'), ('other', 'Outros')], default='other', max_length=30)),
                ('store_name', models.CharField(blank=True, max_length=100)),
                ('product_url', models.URLField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('desired_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('wanted', 'Quero comprar'), ('researching', 'Pesquisando'), ('waiting', 'Aguardando promoção'), ('bought', 'Comprado'), ('cancelled', 'Cancelado')], default='wanted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
        ),
    ]
