# Generated by Django 6.0.3 on 2026-04-09 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_updated_at_category_updated_at_and_more'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['-created_at', 'name']},
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='bought_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='bought_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='financial_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='financial_transaction_created',
            field=models.BooleanField(default=False),
        ),
    ]
